[package]
name = "tabularix"
version = "0.3.4"
edition = "2021"

[lib]
name = "_tabularix"
crate-type = ["cdylib"]

[dependencies]
arrow = { version = "59.0.0", features = ["ffi"] }
calamine = { version = "0.36.0", features = ["chrono"] }
pyo3 = { version = "0.29.0", features = ["abi3-py312"] }
chrono = "0.4.45"
