[settings]
experimental = true
lockfile = true
# Delay upgrading to new versions until they are at least 7 days old to implement a cooldown period.
minimum_release_age = "7d"

[tools]
actionlint = "latest"
cargo-binstall = "latest"
"cargo:cargo-audit" = "latest"
"cargo:maturin" = "latest"
hadolint = "latest"
just = "latest"
node = "latest"
pinact = "latest"
prek = "latest"
usage = "latest"
uv = "latest"
