[settings]
experimental = true
lockfile = true

[tools]
actionlint = "latest"
just = "latest"
node = "latest"
pinact = "latest"
prek = "latest"
python = "latest"
usage = "latest"
rust = { version = "latest", components = "rustfmt,clippy" }
"github:PyO3/maturin" = "latest"
uv = "latest"
