[build-system]
requires = ["maturin>=1.13.3,<2.0"]
build-backend = "maturin"

[project]
name = "tabularix"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "pyarrow>=24.0.0",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "tabularix._tabularix"
python-source = "python"

[tool.uv]
# Delay upgrading to new versions until they are at least 7 days old to implement a cooldown period.
exclude-newer = "7 days"

[dependency-groups]
dev = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "polars>=1.41.2",
    "robotframework>=7.4.2",
]

[tool.fawltydeps]
ignore_unused = ["robotframework", "pandas", "polars"] # TODO: to remove on code samples are written

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
  "I", # isort
  "D", # pydocstyle
]
extend-ignore = [
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
]

[tool.ruff.lint.pydocstyle]
convention = "google"
