[build-system]
requires = ["maturin>=1.14.1,<2.0"]
build-backend = "maturin"

[project]
name = "tabularix"
description = "High-performance framework for layout-resilient Excel table extraction"
version = "0.1.0"
readme = "README.md"
license = { text = "MIT OR Apache-2.0" }
authors = [
    { name = "Pascal Castéran", email = "15686972+pcasteran@users.noreply.github.com" }
]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: Apache Software License",
]
dynamic = ["version"]
keywords = [
    "excel",
    "pyarrow",
    "arrow",
    "pandas",
    "polars",
    "layout-resilient",
    "data-extraction"
]
dependencies = [
    "pyarrow>=24.0.0",
]

[project.urls]
Homepage = "https://github.com/pcasteran/tabularix"
Documentation = "https://pcasteran.github.io/tabularix"
Repository = "https://github.com/pcasteran/tabularix"
"Bug Tracker" = "https://github.com/pcasteran/tabularix/issues"
"Changelog" = "https://github.com/pcasteran/tabularix/blob/main/CHANGELOG.md"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "tabularix._tabularix"
python-source = "python"

[tool.uv]
# Delay upgrading to new versions until they are at least 7 days old to implement a cooldown period.
exclude-newer = "7 days"

[dependency-groups]
dev = [
    "duckdb>=1.5.4",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "polars>=1.42.0",
    "robotframework>=7.4.2",
]

[tool.fawltydeps]
ignore_unused = ["robotframework"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
  "I", # isort
  "D", # pydocstyle
]
extend-ignore = [
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
]

[tool.ruff.lint.pydocstyle]
convention = "google"
